dist: xenial
language: php
sudo: required
php:
- 7.1
branches:
  only:
  - master
  - develop
  - pre-release-travis-test
  - pre-release
  # - codeception

before_install:
- rm -rf ~/.gnupg
- sudo apt-get install xvfb

before_script:

- export PLUGIN_DIR=$(pwd)
- sudo rm -rf /etc/mysql/
- sudo rm -rf /var/lib/mysql/
- sudo apt-get -qq purge mysql* graphviz*
- sudo apt-get --purge remove mysql-server
- sudo apt-get --purge remove mysql-client
- sudo apt-get --purge remove mysql-common
- sudo apt-get autoremove
- sudo apt-get autoclean
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- wget -qO ee rt.cx/ee && sudo bash ee
- sudo ee stack install --nginx
- sudo ee stack install --web
- sudo wp --yes --allow-root cli update --nightly
- sudo ee site create automation.features-for-woocommerce.me --wp --user=ADMINUSER --email=raftaar1191@gmail.com --pass=ADMINPASS
- sudo sed -i '/^127.0.0.1/ s/$/ automation.features-for-woocommerce.me/' /etc/hosts
- sudo chmod 777 -R /var/www
- cd /var/www/automation.features-for-woocommerce.me/htdocs/wp-content/plugins/ && mkdir features-for-woocommerce
- cd $PLUGIN_DIR
- cp -Rf * /var/www/automation.features-for-woocommerce.me/htdocs/wp-content/plugins/features-for-woocommerce/
- cd /var/www/automation.features-for-woocommerce.me/htdocs/
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/woocommerce.zip
- wp plugin activate --all
- cd $PLUGIN_DIR
# - composer update
- composer install
- export PATH="$PATH:/home/travis/build/features-for-woocommerceWP/features-for-woocommerce/tests/codeception/vendor/bin"
## PHP_CodeSniffer
- git clone https://github.com/squizlabs/PHP_CodeSniffer.git
- cd PHP_CodeSniffer
- pear install package.xml
- cd ../
- git clone git://github.com/wimg/PHPCompatibility.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/PHPCompatibility
- phpenv rehash
- phpcs -i
- phpenv rehash
- phpcs --config-set installed_paths $(pear config-get php_dir)/PHP/CodeSniffer/Standards
- phpcs --config-set installed_paths $(pear config-get php_dir)/PHP/CodeSniffer/Standards/PHPCompatibility
- phpcs -i
- phpcs --config-set error_severity 0
- phpcs --config-set warning_severity 0

script:
## PHP_CodeSniffer
- phpcs --standard=PHPCompatibility --runtime-set testVersion 5.3-5.5 $(find ./tests/acceptance -name '*.php')
- if find . -name "*.php" ! -path "./node_modules/*" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
- codecept run acceptance --steps

after_script:
- sudo cat /var/log/ee/ee.log

#notifications:
#  slack:
#    secure: E9tbxOZ/n4Gcwi8SiCKQ5QVw+5AfwdTq4e/VG4epQF74IqXmJJvaJgQSVKLSVXJm4O1u8JHd+ffN1Xheh1FDaKkscuJYQcT4D+oOc40bHhb0tS71v1fAMzMX7NuyqgEu2a8dbYo7bqVKtdj/EBbOPWnwgfMuA6ylTItVf294spA=